### PR TITLE
[ADD] mass_mailing_editor_af, mail_massmail_template_af: AFC-1725 Rem…

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**
…oved one sample template, Added dynamic links on sample template, Added new snippets, Updated some style on sample template.

### CODE REVIEW

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 - Please change name of these modules to comply with Odoos module-name.

mail_mass_mailing_gdrp_limitations -> mass_mailing_gdrp_limitations
mail_massmailing_sender_logs -> mass_mailing_sender_logs
mail_massmailing_statistics_af -> mass_mailing_statistics_af
mail_massmail_matomo_statistics -> mass_mailing_matomo_statistics
mail_massmail_template_af -> mass_mailing_template_af
mail_autoresponder -> mass_mailing_autoresponder
mail_autoresponder_crm -> mass_mailing_autoresponder_crm
mail_installmodules_adkd -> mail_install_modules_adkd

**Comment by fredrikarvas-vertel** [comment]
**Reminder** to the person who merges this. Please uninstall all old versions in all databases before merging.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will do it
Thanks.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

In this PR added one more commit to change mail_massmail_template_af -> mass_mailing_template_af

Please check it and let me know if anything.
Note: Before merge uninstall 
mail_massmail_template_af and Go to Apps, 
search mail_massmail_template_af, select, Go to Action and delete it.

Thanks.
Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
here @HazeLidman

**Comment by HazeLidman** [comment]
hi, it seems like you didn't add 
mass_mailing_editor_af, 
mass_mailing_template_af 
these 2 modules in the depends of mail_install_modules_adkd? 
they should be installed as well when others are installed right? @rupareliyahemangi145  if it's so, plz adde them to depends as well :)

**Comment by rupareliyahemangi145** [comment]
Ok @HazeLidman

**Comment by rupareliyahemangi145** [comment]
Hi @HazeLidman Created PR https://github.com/vertelab/odoo-mail/pull/70 to add module in depends.

Please check it and let me know if anything.
Thanks.

**Comment by HazeLidman** [comment]
image
 mass_mailing_template_af can't not be installed, plz see the attached photo. @rupareliyahemangi145

**Comment by HazeLidman** [comment]
okay merged

**Pull request merged**
